const KEY="franciscoAdminDemo";
const defaultState={admin:{username:"admin",password:"Admin@2026"},grades:[
{id:crypto.randomUUID(),name:"6º ano",enabled:true,classes:[]},
{id:crypto.randomUUID(),name:"7º ano",enabled:true,classes:[]},
{id:crypto.randomUUID(),name:"8º ano",enabled:true,classes:[]},
{id:crypto.randomUUID(),name:"9º ano",enabled:true,classes:[]}
],notices:[],playlist:{},games:{}};
let state=load();
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaultState)}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
const $=s=>document.querySelector(s);
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function login(){if($("#username").value===state.admin.username&&$("#password").value===state.admin.password){sessionStorage.setItem("adminOK","1");$("#loginView").classList.remove("active");$("#appView").classList.add("active");renderAll()}else $("#loginError").textContent="Usuário ou senha incorretos."}
$("#loginForm").addEventListener("submit",e=>{e.preventDefault();login()});
$("#logoutBtn").onclick=()=>{sessionStorage.removeItem("adminOK");location.reload()};
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#tab-"+b.dataset.tab).classList.add("active")});
function openModal(html,onSave){$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden");$("#modalBody form").onsubmit=e=>{e.preventDefault();onSave(new FormData(e.target));$("#modal").classList.add("hidden")}}
$("#closeModal").onclick=()=>$("#modal").classList.add("hidden");
$("#addGradeBtn").onclick=()=>openModal(`<h3>Adicionar ano ou série</h3><form class="form-grid"><label>Nome<input name="name" placeholder="Ex.: 1ª série" required></label><button class="primary">Adicionar</button></form>`,fd=>{state.grades.push({id:crypto.randomUUID(),name:fd.get("name"),enabled:true,classes:[]});save()});
function renderGrades(){$("#gradesList").innerHTML=state.grades.map(g=>`<article class="grade"><div class="grade-head"><div><h3>${esc(g.name)}</h3><span class="meta">${g.classes.length} turma(s) cadastrada(s)</span></div><div class="actions"><button class="mini" onclick="addClass('${g.id}')">+ Turma</button><button class="mini" onclick="editGrade('${g.id}')">Editar</button><button class="mini danger" onclick="delGrade('${g.id}')">Excluir</button></div></div><div class="subclasses">${g.classes.length?g.classes.map(c=>`<div class="subclass"><span><strong>${esc(c.name)}</strong> ${c.loginEnabled?"🔐 login ativo":"— sem login específico"}${c.loginEnabled?`<br><span class="meta">Usuário: ${esc(c.username)}</span>`:""}</span><span class="actions"><button class="mini" onclick="editClass('${g.id}','${c.id}')">Editar</button><button class="mini danger" onclick="delClass('${g.id}','${c.id}')">Excluir</button></span></div>`).join(""):`<span class="muted">Nenhuma turma específica. Os alunos podem entrar diretamente no ${esc(g.name)}.</span>`}</div></article>`).join("")}
function editGrade(id){const g=state.grades.find(x=>x.id===id);openModal(`<h3>Editar ano/série</h3><form class="form-grid"><label>Nome<input name="name" value="${esc(g.name)}" required></label><button class="primary">Salvar</button></form>`,fd=>{g.name=fd.get("name");save()})}
function delGrade(id){if(confirm("Excluir este ano/série e suas turmas?")){state.grades=state.grades.filter(x=>x.id!==id);save()}}
function addClass(gid){const g=state.grades.find(x=>x.id===gid);openModal(`<h3>Adicionar turma em ${esc(g.name)}</h3><form class="form-grid"><label>Nome da turma<input name="name" placeholder="Ex.: 6º A" required></label><label><input name="loginEnabled" type="checkbox"> Ativar login específico</label><label>Usuário da turma<input name="username" placeholder="Ex.: 6a"></label><label>Senha da turma<input name="password" type="text" placeholder="Ex.: Francisco@2026A"></label><button class="primary">Adicionar</button></form>`,fd=>{g.classes.push({id:crypto.randomUUID(),name:fd.get("name"),loginEnabled:fd.get("loginEnabled")==="on",username:fd.get("username")||"",password:fd.get("password")||""});save()})}
function editClass(gid,cid){const g=state.grades.find(x=>x.id===gid),c=g.classes.find(x=>x.id===cid);openModal(`<h3>Editar ${esc(c.name)}</h3><form class="form-grid"><label>Nome<input name="name" value="${esc(c.name)}" required></label><label><input name="loginEnabled" type="checkbox" ${c.loginEnabled?"checked":""}> Ativar login específico</label><label>Usuário<input name="username" value="${esc(c.username)}"></label><label>Senha<input name="password" value="${esc(c.password)}" type="text"></label><button class="primary">Salvar</button></form>`,fd=>{c.name=fd.get("name");c.loginEnabled=fd.get("loginEnabled")==="on";c.username=fd.get("username")||"";c.password=fd.get("password")||"";save()})}
function delClass(gid,cid){const g=state.grades.find(x=>x.id===gid);if(confirm("Excluir esta turma?")){g.classes=g.classes.filter(x=>x.id!==cid);save()}}
function targetOptions(){let a=[`<option value="ALL">Toda a escola</option>`];state.grades.forEach(g=>{a.push(`<option value="G:${g.id}">${esc(g.name)} (todas as turmas)</option>`);g.classes.forEach(c=>a.push(`<option value="C:${c.id}">${esc(c.name)}</option>`))});return a.join("")}
function renderNotices(){$("#noticeTarget").innerHTML=targetOptions();$("#noticesList").innerHTML=state.notices.length?state.notices.slice().reverse().map(n=>`<article class="item"><span class="meta">${esc(n.targetLabel)}</span><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${n.image?`<a href="${esc(n.image)}" target="_blank" rel="noopener">Imagem/link</a>`:""}<div class="actions" style="margin-top:10px"><button class="mini danger" onclick="delNotice('${n.id}')">Excluir</button></div></article>`).join(""):`<p class="muted">Nenhum aviso publicado.</p>`}
$("#noticeForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target),target=fd.get("target"),opt=$("#noticeTarget").selectedOptions[0];state.notices.push({id:crypto.randomUUID(),title:fd.get("title"),text:fd.get("text"),image:fd.get("image"),target,targetLabel:opt.textContent,date:new Date().toLocaleString("pt-BR")});e.target.reset();save()});
function delNotice(id){state.notices=state.notices.filter(n=>n.id!==id);save()}
function renderPlaylist(){$("#playlistList").innerHTML=state.grades.map(g=>{const p=state.playlist[g.id]||{app:"",link:""};return `<article class="item"><h3>${esc(g.name)}</h3><form class="form-grid" onsubmit="savePlaylist(event,'${g.id}')"><label>Aplicativo/serviço<input name="app" value="${esc(p.app)}" placeholder="Spotify, YouTube, etc."></label><label>Link da playlist<input name="link" value="${esc(p.link)}" placeholder="https://..."></label><button class="primary">Salvar playlist</button></form></article>`}).join("")}
function savePlaylist(e,id){e.preventDefault();const fd=new FormData(e.target);state.playlist[id]={app:fd.get("app"),link:fd.get("link")};save();alert("Playlist salva.")}
function renderGames(){$("#gamesList").innerHTML=state.grades.map(g=>{const rows=state.games[g.id]||[];return `<article class="item"><h3>${esc(g.name)}</h3><form class="form-grid" onsubmit="saveGames(event,'${g.id}')"><label class="full">Jogos da semana<textarea name="games" rows="6" placeholder="Segunda: Queimada&#10;Terça: Futebol&#10;Quarta: Basquete">${esc(rows.join("\n"))}</textarea></label><button class="primary">Salvar jogos</button></form></article>`}).join("")}
function saveGames(e,id){e.preventDefault();state.games[id]=new FormData(e.target).get("games").split("\n").map(x=>x.trim()).filter(Boolean);save();alert("Jogos salvos.")}
$("#adminForm").addEventListener("submit",e=>{e.preventDefault();const fd=new FormData(e.target);state.admin.username=fd.get("username");if(fd.get("password"))state.admin.password=fd.get("password");save();alert("Acesso administrativo atualizado.")});
function renderConfig(){$("#adminUsername").value=state.admin.username}
function renderAll(){renderGrades();renderNotices();renderPlaylist();renderGames();renderConfig()}
if(sessionStorage.getItem("adminOK")==="1"){ $("#loginView").classList.remove("active");$("#appView").classList.add("active");renderAll(); }
